-- init.sql
CREATE USER c##fsl3pl IDENTIFIED BY Asdf1234;
GRANT CREATE SESSION TO c##fsl3pl;
GRANT CREATE TABLE TO c##fsl3pl;
GRANT CREATE VIEW TO c##fsl3pl;
GRANT UNLIMITED TABLESPACE TO c##fsl3pl;
GRANT CREATE TYPE TO c##fsl3pl;
GRANT CREATE SEQUENCE TO c##fsl3pl;
GRANT CREATE TRIGGER TO c##fsl3pl;
GRANT CREATE ANY PROCEDURE TO c##fsl3pl;
GRANT EXECUTE ANY PROCEDURE TO c##fsl3pl;

